### ISSUE TITLE
Elegantly exit out of the `serve` command

### ISSUE THREAD

**Issue by gridhead** [CentOS/duffy#100]
Refer https://github.com/CentOS/duffy/pull/97#pullrequestreview-811241312

On raising a `KeyboardInterrupt`, supposedly the event loop abruptly exits out and shows an error. Catching the `KeyboardInterrupt` exception and treating it to close the event loop before destroying it, should do it.

**Comment by nphilipp** [comment]
I'm not sure if catching `KeyboardInterrupt` helps, as it's `asyncio.exceptions.CancelledError` that bubbles to the top and causes the traceback to be shown – my comment in the other PR probably wasn't clear. Let's look if just catching the latter is good practice.

**Comment by nphilipp** [comment]
As we found out in the call, this is an artifact of `--reload` and doesn't look like it's easily fixable (but also not super important as it's an options used for debugging/development). Closing.
