### ISSUE TITLE
Inactive tenants record

### ISSUE THREAD

**Issue by siddharthvipul** [CentOS/duffy#115]
## Story
As a CentOS CI admin, 
I want to be able to keep records of tenants who are not active. Instead of deleting them completely, moving them to another table which signifies "Inactive".

## Acceptance Criteria

- [ ] Active and Inactive tenants have a way to be identified

**Comment by siddharthvipul** [comment]
This can be an extra column with boolean value of active
or a separate table in itself.. upto developer to think what works the best

**Comment by nphilipp** [comment]
Let's make it a simple flag. Moving records between tables will break relationships with e.g. historical sessions.

**Comment by nphilipp** [comment]
…and we have this as part of PR #118 (`retired_at` columns plus `active` property).
