### ISSUE TITLE
Authenticate endpoint access

### ISSUE THREAD

**Issue by nphilipp** [CentOS/duffy#135]
This needs #136.

# Stories

As an admin of Duffy,
I want that the API authenticates its users,
so privileged operations are limited to admins.

As a normal tenant user of Duffy,
I want that the API authenticates requests,
so that only I can request resources on my behalf.

# Acceptance Criteria

- [x] A way exists to define an API key/token per tenant
- [x] API endpoints check token validity and levels of access before performing work
- [x] API endpoints return suitable status codes and error information if an activity that needs authorization is attempted with the wrong or a missing token

# Background

- https://fastapi.tiangolo.com/tutorial/security/first-steps/

**Comment by gridhead** [comment]
@nphilipp, thanks for refining the card. Some design-based questions, I have that I would love to have answers for - before I set out ~on the long and arduous adventure~ to implement authentication.

- Some HTTP methods (like GET etc) do not mask parameters at all while some HTTP methods (like POST etc) mask parameters in Base 64 format (or encoding of such kind). Do we make it mandatory for the clients to hash API keys or tokens before sending those to the Duffy API?

- Do we create specially-defined but empty projects to house API tokens for admin purposes? or Do we simply store it as one of the restricted secrets of the project/repository?

I am likely to come up with more questions but getting answers of these should help me get started. I understand that some of these questions are more of the opinionated kind than the one having defined right or wrong answers.

**Comment by nphilipp** [comment]
As we discussed:

- API Tokens are usually transferred in the headers of a request which aren't logged usually (which is why secrets don't belong into GET/CGI parameters). I strongly assume Duffy will sit behind an HTTP proxy when used in production, so we needn't worry about spilling secrets while in transit either. Some assumptions here, but I think they're sound! :grin: 
- We'll rename "projects" to "tenants", that way we can lump admins together with project users and not stretch the metaphor too far (#136).

**Comment by gridhead** [comment]
Now that https://github.com/CentOS/duffy/pull/138 and https://github.com/CentOS/duffy/pull/142, this ticket can be safely stated to be in an "unblocked" state, unless someone comes up with some more design-based questions that need answering before a pull request addressing this PR can be merged.

Let me help with those questions.

1. For normal tenants - 
   1. Which endpoints **should be accessible** to the tenants and which endpoints **should not be**?
   2. Which endpoints **make it necessary to require** an API key, which ones can have **different outputs on the basis of its presence or absence** and which ones **absolutely do not require** an API key - for the tenants to operate?
2. For admin tenants - 
   1. Which endpoints **should be accessible** to the tenants and which endpoints **should not be**?
   2. Which endpoints **make it necessary to require** an API key, which ones can have **different outputs on the basis of its presence or absence** and which ones **absolutely do not require** an API key - for the tenants to operate?
