### ISSUE TITLE
Rework tenants table to have an API key column

### ISSUE THREAD

**Issue by gridhead** [CentOS/duffy#145]
The API key would be used to authenticate the normal tenants as well as the admin tenants for certain operations that require authorization.

**Comment by gridhead** [comment]
Some design-based questions.
1. Do we want it to be a UUID or a 64 byte hexadecimal string?
	Examples
	1. For UUID
		```
		>>> import uuid
		>>> print(uuid.uuid4())
		2d4b9f2b-ad45-484f-a0a6-75393bacba4c
		```
	2. For 64 byte hexadecimal string
		```
		>>> from hashlib import sha256
		>>> from time import time
		>>> print(sha256(str(time()).encode()).hexdigest())
		cbcf10bea3e6c80425e14b95de4ff789d9f6323433050157eb40ad3fb931fb3f
		```
2. Do we want to mask it before storage or do we store it as a plain text?

**Comment by nphilipp** [comment]
As we discussed in the call, I would opt for a uuid – it's very easy to generate, `uuidgen` is part of the `util-linux` package – and to store it cryptographically hashed, e.g. using [bcrypt](https://pypi.org/project/bcrypt/). Not in the scope of this ticket, but we may have to cache this in some way – the bcrypt operations are intentionally slow, and if we e.g. cached successfully authenticated tenant-token pairs in process, only the first in a row of queries would incur that overhead.
