### ISSUE TITLE
Document differences between old and new Duffy

### ISSUE THREAD

**Issue by nphilipp** [CentOS/duffy#252]
# Story

As a stakeholder in Duffy,
I want to know how the new version differs from the old one,
so I can be confident that the effort was justified.

# Acceptance Criteria

- [x] A publicly accessible document exists which describes how the new version of Duffy is better than the old one (10,000ft view).

**Comment by gridhead** [comment]
I added https://github.com/CentOS/duffy/wiki/What's-new%3F. Please feel free to take a look and suggest changes.

**Comment by nphilipp** [comment]
https://github.com/CentOS/duffy/wiki/What's-New%3F
