### ISSUE TITLE
Dump old MySQL database to CSV to prepare import into PostgreSQL

### ISSUE THREAD

**Issue by gridhead** [CentOS/duffy#304]
# Story

As a Duffy developer,
I want a CSV dump of relevant legacy data that needs to be migrated into the new Duffy,
so I can write the scripts.

# Acceptance Criteria

CSV dumps of the following tables in the legacy Duffy database:
- [x] users
- [x] userkeys

# Background

The information about the existing tenants including their UUIDs, SSH public keys need to exported to CSVs for easier importing to the newer Postgres database.

**Comment by nphilipp** [comment]
This is done – we tested the import script yesterday with the dumps. When we get to deployment, we can easily create up-to-date dumps again.
