### ISSUE TITLE
Clean up Branches

### ISSUE THREAD

**Issue by nphilipp** [CentOS/duffy#42]
# Stories

1. As a contributor to Duffy,
I want that branches are named descriptively,
so that I make changes in the right place.

2. As a contributor to Duffy,
I want that cloning the repository checks out the branch where development happens,
so I make my contributions in the right place.

3. As a contributor to Duffy,
I want stale branches to be clearly named as such,
so I don't waste time with them. 

# Acceptance Criteria

- [x] All existing branches are moved to a `stale` namespace, i.e. renamed to `stale/<branch name>`
- [x] An empty `dev` branch is created
- [x] The `dev` branch is made the default branch

# Background

We want to do this from scratch, so all existing content should be moved out of the way. Besides that, `master` is a loaded term and doesn't really tell you the purpose of this branch.

**Comment by siddharthvipul** [comment]
@nphilipp can you check once to see if things are looking okay

**Comment by nphilipp** [comment]
@siddharthvipul looks good to me!
