### ISSUE TITLE
Project Boilerplate

### ISSUE THREAD

**Issue by nphilipp** [CentOS/duffy#43]
# Story

As a contributor to Duffy,
I want basic “Python project boilerplate” in place,
so I can actually develop something.

# Acceptance Criteria

The repository is set up …:

- [x] … with a top-level directory for the code and another for its tests
- [x] … to use poetry for installing it and its dependencies (see below)
- [x] … to use `pytest` and its `cov` plugin for testing and verifying coverage
- [x] … so `black` assumes a line length of 100 characters
- [x] … so `.gitignore` ignores some commonly generated files and directories
- [x] … so `pytest-black`, `pytest-flake8` and `pytest-isort` are dev deps and configured to be run with `pytest`

# Background

Status: Everything is an empty void.

# Background (serious)

These are the dependencies with which we want to build Duffy:

- `fastapi` as the web microframework
- `sqlalchemy` as the ORM encapsulating DB operations
- `psycopg2` to use PostgreSQL
- `pytest`, `pytest-cov` for testing
- `tox` for running the tests, linting etc. in different environments

**Comment by nphilipp** [comment]
Picking up the basic package, test & black configuration.

**Comment by gridhead** [comment]
Should we add CI (with GitHub actions) to the mix? General black and isort checks.

**Comment by nphilipp** [comment]
I added CI as a card into `New`, just have to convert it to an issue and flesh it out.

**Comment by nphilipp** [comment]
I'll add pytest-black, pytest-isort and configure pytest to run them here, though. :smiley:

**Comment by gridhead** [comment]
Makes sense.

**Comment by nphilipp** [comment]
…and pytest-flake8 :grin:

**Comment by nphilipp** [comment]
Here's the PR: #51 

Note: It's based on #50 which needs to be merged before it.
