### ISSUE TITLE
Document setting up project locally 

### ISSUE THREAD

**Issue by gridhead** [CentOS/duffy#45]
# Story

As a contributor to Duffy,
I want to be able to set the project up locally,
so I can actually develop something.

# Acceptance Criteria

The repository is set up …:

- [x] … with installation instructions for local development environment
 
# Background

Status: We have the Poetry boilerplate.

# Background (serious)

We use Poetry for dependency management so our instructions would hail from there.

**Comment by nphilipp** [comment]
PR: #48 (in lieu of #46 which I broke)
