### ISSUE TITLE
Implement CI for the project

### ISSUE THREAD

**Issue by siddharthvipul** [CentOS/duffy#52]
# Story

As a contributor to Duffy,
I want CI jobs to be in place,
so my contributions are tested automatically when I submit them as PRs.

# Acceptance Criteria

- [x] A suitable framework from the alternatives (Jenkins, GH actions, …) has been chosen
- [x] The basic structure to run CI jobs has been set up

# Background

Potential candidates and options we can use:

- Jenkins
- dependabot
- LGTM

**Comment by gridhead** [comment]
Closed via #60
