### ISSUE TITLE
Expose user endpoint

### ISSUE THREAD

**Issue by BenCapper** [CentOS/duffy#80]
Expose API endpoint to add/edit/delete Users

- #77

# Acceptance Criteria

Implement…
- [ ] a `GET` method to list items of the type
- [ ] a `POST` method to create new items of the type
- [ ] a `PUT` method to update items of the type
- [ ] a `DELETE` method to delete items of a type (only where applicable?)

**Comment by nphilipp** [comment]
This one is moot as we don't care about individual users anymore – on the DB level at least, we love our users!
