### ISSUE TITLE
Expose `node` endpoint

### ISSUE THREAD

**Issue by BenCapper** [CentOS/duffy#89]
- #77

# Acceptance Criteria

Implement…
- [x] a `GET` method to list items of the type
- [x] a `POST` method to create new items of the type
- [x] a `DELETE` method to delete items of a type (only where applicable?)

**Comment by nphilipp** [comment]
As discussed, we don't want separate endpoints for bare-metal vs. virtual machines. Re-scoping this one, closing #90.
