### ISSUE TITLE
Expose physical hardware endpoint

### ISSUE THREAD

**Issue by BenCapper** [CentOS/duffy#90]
- #77

# Acceptance Criteria

Implement…
- [ ] a `GET` method to list items of the type
- [ ] a `POST` method to create new items of the type
- [ ] a `PUT` method to update items of the type
- [ ] a `DELETE` method to delete items of a type (only where applicable?)

**Comment by nphilipp** [comment]
This one's moot, we want to have one API endpoint for all types of noes.
